### ISSUE TITLE
No license, this should have one

### ISSUE THREAD

**Issue by sreid8** [dex4er/upstart-dummy#2]
I think this project should be licensed. Personally, I'd be interested in seeing it licensed under MIT or Apache 2.0

**Comment by dex4er** [comment]
Hi. It was not my project and I just put it on github few years ago with my additional modifications. I see the original author was Péter Gyöngyösi and I'll try to contact him and ask him about license.

**Comment by sreid8** [comment]
I definitely appreciate it. This is a very useful project, thanks for putting it up

**Comment by dex4er** [comment]
Thank you, @gyp !
